#!/usr/bin/env bash

# We need this extra script run ONCE on startup to initialize the
# database with per-image passwords.

export DEBIAN_FRONTEND=noninteractive

MYSQL_ROOT_PASSWORD=$(head /dev/urandom -c 512 | sha1sum | awk '// { print $1; }')
dbname="wordpress"

# MOTD & README
sed -i "s/{mysql_root_password}/$MYSQL_ROOT_PASSWORD/" /etc/update-motd.d/70-wordpress
sed -i "s/{mysql_root_password}/$MYSQL_ROOT_PASSWORD/" /root/README

# Configure wordpress database
sed -i "s/define('DB_NAME',.*/define('DB_NAME', '$dbname');/" /var/www/wp-config.php
sed -i "s/define('DB_USER',.*/define('DB_USER', 'root');/" /var/www/wp-config.php
sed -i "s/define('DB_PASSWORD',.*/define('DB_PASSWORD', '$MYSQL_ROOT_PASSWORD');/" /var/www/wp-config.php
sed -i "/WP_DEBUG/a\\define('FS_METHOD', 'direct');" /var/www/wp-config.php
chown -R www-data /var/www/

# Configure postfix
sed -i "s/mydestination = .*/mydestination = $(/usr/local/bin/oc-metadata --cached ID).pub.cloud.scaleway.com, localhost.localdomain, localhost/g" /etc/postfix/main.cf
sed -i "s/myhostname = .*/myhostname = $(/usr/local/bin/oc-metadata --cached ID).pub.cloud.scaleway.com/g" /etc/postfix/main.cf
sed -i "s/inet_interfaces = .*/inet_interfaces = localhost/g" /etc/postfix/main.cf

postfix -c /etc/postfix/ set-permissions
chown -R root:postdrop /usr/sbin/postqueue
chown -R root:postdrop /usr/sbin/postdrop
chmod g+s /usr/sbin/postqueue /usr/sbin/postdrop
/etc/initd.d/postfix start

# Let's install MySQL
chmod 1777 /tmp
/etc/init.d/mysql start
mysqladmin -u root password $MYSQL_ROOT_PASSWORD

# this service is only needed on the first boot so we remove it here.
rm -f /etc/init/init-wordpress.conf
rm -f /usr/local/sbin/oc-init-wordpress
